services:
  frontend:
    build:
      context: .  # Cambia el contexto a la raíz del proyecto donde está docker-compose.yml
      dockerfile: TeraFrontendMVC/Dockerfile  # Indica la ubicación del Dockerfile
    ports:
      - "8081:80"  # Exponer el puerto 80 del contenedor al puerto 8081 del host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
